#!/usr/bin/env bash
#
# **rerun** - If you've got a bunch of loose
# unstructured shell scripts, rerun will help you
# turn them into testable automation modules.
#
# Minimalism is rerun's goal. It will try to stay out of your way
# yet take care of some of your grunt work.
#
#/ usage: rerun [-h][-G][-x][-v][-V][--version] [--loglevel <>] [-M <dir>] [--answers|-A <file>] [--sudo-user|-S <user>] [module:[command [options]]]
#
# __Install__
#
# See [wiki](http://github.com/rerun/rerun/wiki) for install and
# setup instructions.

source "$RERUN_ROOT_PATH/man/core/variable.sh"
source "$RERUN_ROOT_PATH/man/core/function/public.sh"

# Check if this file is being sourced, or executed.
# If not being executed, return now.
if [[ "${BASH_SOURCE:-}" != "$0" && "$0" != "bash" ]]
then
    return; # Stop sourcing the file here.
fi


# Enable a stringent exeuction environment.
#
set -u ; # Exit if unassigned variable accessed.
set -e ; # Exit if command execution fails.


source "$RERUN_ROOT_PATH/man/core/function/private.sh"

source "$RERUN_ROOT_PATH/man/core/options.sh"

source "$RERUN_ROOT_PATH/man/core/module.sh"

source "$RERUN_ROOT_PATH/man/core/execute.sh"